openapi: 3.0.3
info:
  description: Currency conversion calculation service.
  contact:
    email: karabaevmb@gmail.com
  title: Betoola Homework API
  version: 0.0.1
servers:
  - url: http:localhost:8080
tags:
  - name: Exchange
paths:
  /rest/exchange:
    post:
      tags:
        - Exchange
      summary: Exchange Currency1 for Specified Amount of Currency2
      operationId: exchange
      parameters:
        - name: currencyForSale
          in: query
          description: Currency that client want to sale
          required: true
          schema:
            $ref: '#/components/schemas/CurrencyCode'
        - name: amountForSale
          in: query
          description: Amount of currency for sale
          required: true
          schema:
            type: number
            format: int64
        - name: targetCurrency
          in: query
          description: Target currency after exchange
          required: true
          schema:
            $ref: '#/components/schemas/CurrencyCode'
      responses:
        200:
          content:
            text/plain:
              schema:
                type: string
          description: Success
        400:
          content:
            text/plain:
              schema:
                type: string
          description: Validation failed
        404:
          content:
            text/plain:
              schema:
                type: string
          description: Entity not found
components:
  schemas:
    CurrencyCode:
      enum:
        - EUR
        - GBP
      type: string
